Adding firewall example. Stable state with amalthea [firewall/iptables]

diff --git a/apps/Arm/vm_multi/network/setup-scripts/generate-client-vlan b/apps/Arm/vm_multi/network/setup-scripts/generate-client-vlan
--- a/apps/Arm/vm_multi/network/setup-scripts/generate-client-vlan
+++ b/apps/Arm/vm_multi/network/setup-scripts/generate-client-vlan
@@ -49,32 +49,16 @@ while [[ $# -gt 0 ]]; do
         show_help
         exit 0
         ;;
+    *)
+        echo "Unknown cli: $1. Exiting"
+        exit 1
   esac
 done
 
 
-# Parse positional arguments
-if [[ -z $node && $# -ge 1 ]]; then
-    node="$1"
-    shift
-fi
-if [[ -z $dev && $# -ge 1 ]]; then
-    dev="$1"
-    shift
-fi
-if [[ -z $ip && $# -ge 1 ]]; then
-    ip="$1"
-    shift
-fi
-if [[ -z $vid && $# -ge 1 ]]; then
-    vid="$1"
-    shift
-fi
-
-
 # Verify we have all the arguments
-if [[ -z $node || -z $dev || -z $ip || -z $vid ]]; then
-    echo "Error: node, dev, ip, and vid are required."
+if [[ -z $node || -z $dev || -z $vid ]]; then
+    echo "Error: node, dev, and vid are required."
     show_help
     exit 1
 fi
@@ -90,6 +74,8 @@ echo sshpass -p "root" dbclient -y $node "ip link set dev $dev.$vid address $ran
 sshpass -p "root" dbclient -y $node "ip link set dev $dev.$vid up"
 echo sshpass -p "root" dbclient -y $node "ip link set dev $dev.$vid up"
 
-sshpass -p "root" dbclient -y $node "ip addr add $ip dev $dev.$vid"
-echo sshpass -p "root" dbclient -y $node "ip addr add $ip dev $dev.$vid"
+if [ -n "$ip" ]; then
+    sshpass -p "root" dbclient -y $node "ip addr add $ip dev $dev.$vid"
+    echo sshpass -p "root" dbclient -y $node "ip addr add $ip dev $dev.$vid"
+fi
 
